version: "3"
services:
  dictionary:
    image: registry.gitlab.com/cmu_sidecar/docuscope-dictionary:latest
    ports:
      - "4000:80"
  couchdb:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=guest
      - COUCHDB_PASSWORD=guest
    ports:
      - "5984:5984"
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  memcached:
    image: memcached:alpine
  tagger:
    image: registry.gitlab.com/cmu_sidecar/docuscope-tag:master
    ports:
      - "4004:80"
    depends_on:
      - rabbitmq
      - couchdb
      - dictionary
  celery:
    image: registry.gitlab.com/cmu_sidecar/docuscope-tag:master-task
    depends_on:
      - rabbitmq
      - couchdb
      - dictionary
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COUCHDB_USER=guest
      - COUCHDB_PASSWORD=guest
      - COUCHDB_URL=http://couchdb:5984/
    ports:
      - "4444:80"
    depends_on:
      - dictionary
      - couchdb
      - tagger